import type { FunnelNodeType, NodeConfig } from './types'

// ─── Colores por categoría ───────────────────────────────────────────────────

export const NODE_COLORS: Record<string, { bg: string; border: string; text: string; icon: string; badge: string }> = {
  traffic:   { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#60a5fa', badge: 'bg-zinc-800 text-zinc-400' },
  pages:     { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#4ade80', badge: 'bg-zinc-800 text-zinc-400' },
  sales:     { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#f97316', badge: 'bg-orange-950 text-orange-400' },
  followup:  { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#a3a3a3', badge: 'bg-zinc-800 text-zinc-500' },
  utilities: { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#a3a3a3', badge: 'bg-zinc-800 text-zinc-600' },
  content:   { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#4ade80', badge: 'bg-zinc-800 text-zinc-400' },
  ai:        { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#c084fc', badge: 'bg-zinc-800 text-zinc-400' },
  tracking:  { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#a3a3a3', badge: 'bg-zinc-800 text-zinc-500' },
  postsale:  { bg: '#1e1e1e', border: '#2e2e2e', text: '#777', icon: '#34d399', badge: 'bg-zinc-800 text-zinc-400' },
}

// ─── Definiciones de cada tipo de nodo ──────────────────────────────────────

export interface NodeDefinition {
  type: FunnelNodeType
  label: string
  category: 'traffic' | 'pages' | 'sales' | 'followup' | 'utilities' | 'content' | 'ai' | 'tracking' | 'postsale'
  description: string
  icon: string                   // nombre del ícono de lucide-react
  hasYesNoOutput: boolean        // si tiene split yes/no
  hasSingleOutput: boolean       // si tiene una sola salida
  hasBranchOutput: boolean       // para nodo split
  hasInput: boolean
  defaultConfig: NodeConfig
  fields: NodeFieldDef[]
}

export interface NodeFieldDef {
  key: string
  label: string
  type: 'number' | 'percentage' | 'currency' | 'select' | 'text'
  min?: number
  max?: number
  step?: number
  tooltip?: string
  benchmark?: string
  options?: Array<{ value: string; label: string }>
  unit?: string
  path?: string  // para campos anidados (ej: branches.0.percentage)
}

export const NODE_DEFINITIONS: Record<FunnelNodeType, NodeDefinition> = {
  trafficSource: {
    type: 'trafficSource',
    label: 'Fuente de Tráfico',
    category: 'traffic',
    description: 'Origen del tráfico: ads pagados, orgánico, email, etc.',
    icon: 'Megaphone',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: {
      platform: 'facebook',
      costModel: 'cpc',
      budget: 1000,
      cpc: 0.50,
      cpm: 10,
      ctr: 2,
      monthlyVisitors: 5000,
    },
    fields: [
      {
        key: 'platform',
        label: 'Plataforma',
        type: 'select',
        options: [
          { value: 'facebook', label: 'Facebook / Instagram Ads' },
          { value: 'google', label: 'Google Ads' },
          { value: 'tiktok', label: 'TikTok Ads' },
          { value: 'organic', label: 'Tráfico Orgánico / SEO' },
          { value: 'email', label: 'Email Marketing' },
          { value: 'whatsapp', label: 'WhatsApp' },
          { value: 'sms', label: 'SMS Marketing' },
          { value: 'referral', label: 'Referidos' },
          { value: 'other', label: 'Otro' },
        ],
        tooltip: 'La fuente de donde proviene el tráfico',
      },
      {
        key: 'costModel',
        label: 'Modelo de costo',
        type: 'select',
        options: [
          { value: 'cpc', label: 'CPC (Costo por clic)' },
          { value: 'cpm', label: 'CPM (Costo por mil impresiones)' },
          { value: 'organic', label: 'Orgánico (sin costo)' },
        ],
        tooltip: 'Cómo se calcula el costo del tráfico',
      },
      {
        key: 'budget',
        label: 'Presupuesto mensual',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 100,
        tooltip: 'Cuánto invertís por mes en esta fuente de tráfico',
        benchmark: 'Presupuesto mínimo recomendado para Facebook: $300-500/mes',
      },
      {
        key: 'cpc',
        label: 'CPC (costo por clic)',
        type: 'currency',
        min: 0.01,
        max: 50,
        step: 0.01,
        tooltip: 'Costo promedio por cada clic en tu anuncio',
        benchmark: 'Facebook Ads: $0.30-$1.50 | Google Ads: $0.50-$5.00 | TikTok: $0.20-$1.00',
      },
      {
        key: 'cpm',
        label: 'CPM (costo por mil)',
        type: 'currency',
        min: 1,
        max: 100,
        step: 0.5,
        tooltip: 'Costo por cada 1,000 impresiones de tu anuncio',
        benchmark: 'Facebook: $8-15 | Instagram: $10-20 | TikTok: $6-12',
      },
      {
        key: 'ctr',
        label: 'CTR (tasa de clics)',
        type: 'percentage',
        min: 0.1,
        max: 20,
        step: 0.1,
        tooltip: 'Porcentaje de personas que hacen clic al ver tu anuncio',
        benchmark: 'Facebook: 1-3% | Google Search: 3-7% | TikTok: 1-2%',
      },
      {
        key: 'monthlyVisitors',
        label: 'Visitantes mensuales',
        type: 'number',
        min: 100,
        max: 1000000,
        step: 100,
        tooltip: 'Visitantes orgánicos estimados por mes',
        benchmark: 'Depende del SEO, redes sociales y autoridad del sitio',
      },
    ],
  },

  landingPage: {
    type: 'landingPage',
    label: 'Landing Page / Opt-in',
    category: 'pages',
    description: 'Página de captura de leads o suscriptores',
    icon: 'FileText',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      conversionRate: 30,
      bounceRate: 55,
    },
    fields: [
      {
        key: 'conversionRate',
        label: 'Tasa de conversión',
        type: 'percentage',
        min: 0.1,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de visitantes que completan el formulario / se suscriben',
        benchmark: 'Landing pages promedio: 20-40% | Top performers: 50-70%',
      },
      {
        key: 'bounceRate',
        label: 'Tasa de rebote',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de visitantes que salen sin interactuar (informativo)',
        benchmark: 'Promedio: 50-70% | Bueno: menos de 40%',
      },
    ],
  },

  salesPage: {
    type: 'salesPage',
    label: 'Página de Ventas',
    category: 'pages',
    description: 'Página donde se presenta y vende la oferta principal',
    icon: 'Monitor',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      conversionRate: 3,
      price: 97,
    },
    fields: [
      {
        key: 'conversionRate',
        label: 'Tasa de conversión',
        type: 'percentage',
        min: 0.1,
        max: 30,
        step: 0.1,
        tooltip: 'Porcentaje de visitantes que compran en esta página',
        benchmark: 'Sales pages: 1-5% | Con video: 3-8% | Alta ticket: 1-2%',
      },
      {
        key: 'price',
        label: 'Precio del producto',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 1,
        tooltip: 'Precio de venta de tu oferta principal',
        benchmark: 'Infoproductos: $27-$497 | Software: $37-$197/mes | Servicios: $500-$5000',
      },
    ],
  },

  checkout: {
    type: 'checkout',
    label: 'Checkout',
    category: 'sales',
    description: 'Proceso de pago con abandono y comisiones',
    icon: 'CreditCard',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      price: 97,
      abandonmentRate: 65,
      processorFee: 3.5,
    },
    fields: [
      {
        key: 'price',
        label: 'Precio del producto',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 1,
        tooltip: 'Precio que el cliente paga en el checkout',
      },
      {
        key: 'abandonmentRate',
        label: 'Tasa de abandono',
        type: 'percentage',
        min: 0,
        max: 99,
        step: 1,
        tooltip: 'Porcentaje de personas que llegan al checkout pero no completan el pago',
        benchmark: 'E-commerce promedio: 65-75% | Con recuperación: 50-60%',
      },
      {
        key: 'processorFee',
        label: 'Comisión del procesador',
        type: 'percentage',
        min: 0,
        max: 15,
        step: 0.1,
        tooltip: 'Porcentaje que cobra Stripe, PayPal, etc. por cada transacción',
        benchmark: 'Stripe: 2.9% + $0.30 | PayPal: 3.5% | Hotmart: 9.9%',
      },
    ],
  },

  upsell: {
    type: 'upsell',
    label: 'Upsell',
    category: 'sales',
    description: 'Oferta adicional post-compra (producto complementario)',
    icon: 'TrendingUp',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      price: 197,
      acceptanceRate: 25,
    },
    fields: [
      {
        key: 'price',
        label: 'Precio del upsell',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 1,
        tooltip: 'Precio de la oferta adicional post-compra',
        benchmark: 'Típico: 2-3x el precio del producto principal',
      },
      {
        key: 'acceptanceRate',
        label: 'Tasa de aceptación',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de compradores que aceptan el upsell',
        benchmark: 'Promedio: 15-35% | Con video: 25-40%',
      },
    ],
  },

  downsell: {
    type: 'downsell',
    label: 'Downsell',
    category: 'sales',
    description: 'Oferta alternativa si rechazan el upsell (menor precio)',
    icon: 'TrendingDown',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      price: 47,
      acceptanceRate: 35,
    },
    fields: [
      {
        key: 'price',
        label: 'Precio del downsell',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 1,
        tooltip: 'Precio de la oferta alternativa (generalmente más barata)',
        benchmark: 'Típico: 1/3 a 1/2 del precio del upsell rechazado',
      },
      {
        key: 'acceptanceRate',
        label: 'Tasa de aceptación',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de personas que aceptan el downsell',
        benchmark: 'Promedio: 25-45% (suelen tener mayor tasa que upsells)',
      },
    ],
  },

  orderBump: {
    type: 'orderBump',
    label: 'Order Bump',
    category: 'sales',
    description: 'Oferta adicional en el mismo checkout (checkbox)',
    icon: 'ShoppingBag',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      price: 27,
      acceptanceRate: 30,
    },
    fields: [
      {
        key: 'price',
        label: 'Precio del order bump',
        type: 'currency',
        min: 0,
        max: 1000,
        step: 1,
        tooltip: 'Precio de la oferta adicional en el checkout',
        benchmark: 'Típico: $7-$67. Debe ser de bajo precio y alta percepción de valor',
      },
      {
        key: 'acceptanceRate',
        label: 'Tasa de aceptación',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de compradores que marcan el order bump',
        benchmark: 'Promedio: 20-40% cuando es relevante y de bajo precio',
      },
    ],
  },

  emailSequence: {
    type: 'emailSequence',
    label: 'Secuencia de Emails',
    category: 'followup',
    description: 'Secuencia de follow-up automatizada por email',
    icon: 'Mail',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      mode: 'sequence',
      emails: 7,
      openRate: 25,
      ctr: 3,
      conversionRate: 5,
    },
    fields: [
      {
        key: 'emails',
        label: 'Cantidad de emails',
        type: 'number',
        min: 1,
        max: 100,
        step: 1,
        tooltip: 'Número de emails en la secuencia automática',
        benchmark: 'Secuencias típicas: 5-14 emails | Welcome series: 3-5 emails',
      },
      {
        key: 'openRate',
        label: 'Tasa de apertura',
        type: 'percentage',
        min: 0.1,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de suscriptores que abren tus emails',
        benchmark: 'Promedio industria: 20-30% | Bueno: 30-45% | Excelente: +50%',
      },
      {
        key: 'ctr',
        label: 'CTR del email',
        type: 'percentage',
        min: 0.1,
        max: 50,
        step: 0.1,
        tooltip: 'Porcentaje de lectores que hacen clic en el link del email',
        benchmark: 'Promedio: 2-5% | Bueno: 5-10% | Con segmentación: 10-20%',
      },
      {
        key: 'conversionRate',
        label: 'Conversión de la secuencia',
        type: 'percentage',
        min: 0.1,
        max: 50,
        step: 0.1,
        tooltip: 'Porcentaje de clics que terminan comprando a través de la secuencia',
        benchmark: 'Promedio: 2-8% | Con buen seguimiento: 5-15%',
      },
    ],
  },

  whatsappSms: {
    type: 'whatsappSms',
    label: 'WhatsApp / SMS',
    category: 'followup',
    description: 'Mensajería directa por WhatsApp o SMS',
    icon: 'MessageCircle',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      deliveryRate: 90,
      responseRate: 40,
      conversionRate: 15,
    },
    fields: [
      {
        key: 'deliveryRate',
        label: 'Tasa de entrega',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de mensajes que llegan al destinatario',
        benchmark: 'WhatsApp: 90-98% | SMS: 85-95%',
      },
      {
        key: 'responseRate',
        label: 'Tasa de respuesta',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de personas que responden o interactúan con el mensaje',
        benchmark: 'WhatsApp: 35-60% | SMS: 20-40%',
      },
      {
        key: 'conversionRate',
        label: 'Tasa de conversión',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de respuestas que terminan en venta o acción deseada',
        benchmark: 'Depende del producto: 10-30% para conversaciones directas',
      },
    ],
  },

  webinarVsl: {
    type: 'webinarVsl',
    label: 'Webinar / VSL',
    category: 'followup',
    description: 'Video de venta (VSL) o webinar en vivo / evergreen',
    icon: 'Video',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      attendanceRate: 30,
      watchRate: 60,
      conversionRate: 10,
      price: 497,
    },
    fields: [
      {
        key: 'attendanceRate',
        label: 'Tasa de asistencia',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de registrados que asisten al webinar',
        benchmark: 'Webinar en vivo: 20-40% | Evergreen automático: 40-70%',
      },
      {
        key: 'watchRate',
        label: 'Tasa de visualización',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de asistentes que ven hasta la oferta (70-80% del video)',
        benchmark: 'VSL: 40-70% | Webinar: 50-80% para quienes se quedan',
      },
      {
        key: 'conversionRate',
        label: 'Tasa de conversión',
        type: 'percentage',
        min: 0,
        max: 50,
        step: 0.5,
        tooltip: 'Porcentaje de los que ven la oferta que terminan comprando',
        benchmark: 'VSL frío: 2-5% | Webinar cálido: 5-15% | Alta confianza: 10-25%',
      },
      {
        key: 'price',
        label: 'Precio del producto',
        type: 'currency',
        min: 0,
        max: 100000,
        step: 1,
        tooltip: 'Precio del producto vendido en el webinar/VSL',
      },
    ],
  },

  retargeting: {
    type: 'retargeting',
    label: 'Retargeting',
    category: 'traffic',
    description: 'Campaña de re-impacto a visitantes que no convirtieron',
    icon: 'RotateCcw',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      captureRate: 60,
      cpc: 0.30,
      conversionRate: 8,
    },
    fields: [
      {
        key: 'captureRate',
        label: 'Tasa de captura',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de no-conversores a los que realmente alcanzás con el retargeting',
        benchmark: 'Pixel bien configurado: 60-80% de alcance',
      },
      {
        key: 'cpc',
        label: 'CPC de retargeting',
        type: 'currency',
        min: 0.01,
        max: 20,
        step: 0.01,
        tooltip: 'Costo por clic en los anuncios de retargeting (suele ser menor que tráfico frío)',
        benchmark: 'Facebook retargeting: $0.15-$0.60 | Google retargeting: $0.25-$1.00',
      },
      {
        key: 'conversionRate',
        label: 'Tasa de conversión',
        type: 'percentage',
        min: 0,
        max: 50,
        step: 0.5,
        tooltip: 'Porcentaje que convierte al re-impactarlos',
        benchmark: 'Retargeting suele ser 2-4x más efectivo que tráfico frío: 5-20%',
      },
    ],
  },

  appointment: {
    type: 'appointment',
    label: 'Cita / Booking',
    category: 'sales',
    description: 'Agendar llamada de ventas o consulta',
    icon: 'Calendar',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      bookingRate: 20,
      showRate: 70,
      closeRate: 30,
      price: 2000,
    },
    fields: [
      {
        key: 'bookingRate',
        label: 'Tasa de booking',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 0.5,
        tooltip: 'Porcentaje de visitantes que agendan una llamada/consulta',
        benchmark: 'Landing de booking bien optimizada: 10-30%',
      },
      {
        key: 'showRate',
        label: 'Tasa de presentación',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de citas agendadas en las que el prospecto realmente se presenta',
        benchmark: 'Con recordatorios por WhatsApp/SMS: 65-80%',
      },
      {
        key: 'closeRate',
        label: 'Tasa de cierre',
        type: 'percentage',
        min: 0,
        max: 100,
        step: 1,
        tooltip: 'Porcentaje de llamadas en que cerrás la venta',
        benchmark: 'Vendedor promedio: 20-30% | Buen vendedor: 35-50%',
      },
      {
        key: 'price',
        label: 'Precio del servicio',
        type: 'currency',
        min: 0,
        max: 1000000,
        step: 100,
        tooltip: 'Precio del servicio o producto high-ticket vendido en la llamada',
      },
    ],
  },

  split: {
    type: 'split',
    label: 'Segmentación / Split',
    category: 'utilities',
    description: 'Divide el tráfico en múltiples ramas',
    icon: 'GitBranch',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: true,
    hasInput: true,
    defaultConfig: {
      branches: [
        { id: 'branch-0', label: 'Rama A', percentage: 50 },
        { id: 'branch-1', label: 'Rama B', percentage: 50 },
      ],
    },
    fields: [],
  },

  result: {
    type: 'result',
    label: 'Resultado',
    category: 'utilities',
    description: 'Nodo terminal que muestra métricas acumuladas',
    icon: 'BarChart3',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {
      label: 'Resultado Final',
    },
    fields: [
      {
        key: 'label',
        label: 'Etiqueta',
        type: 'text',
        tooltip: 'Nombre descriptivo para este nodo de resultado',
      },
    ],
  },

  // ─── New traffic sources ────────────────────────────────────────────────────

  reels: {
    type: 'reels',
    label: 'Reels / TikToks',
    category: 'traffic',
    description: 'Tráfico orgánico desde videos cortos (Reels, TikTok)',
    icon: 'Film',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'instagram', reach: 10000, engagementRate: 5, ctr: 2 },
    fields: [
      { key: 'platform', label: 'Plataforma', type: 'text', tooltip: 'Red social (instagram, tiktok, youtube)' },
      { key: 'reach', label: 'Alcance mensual', type: 'number', min: 0, max: 10000000, step: 100, tooltip: 'Vistas mensuales promedio' },
      { key: 'engagementRate', label: 'Engagement', type: 'percentage', min: 0, max: 100, step: 0.1, benchmark: 'Reels: 3-8% | TikTok: 5-12%' },
      { key: 'ctr', label: 'CTR a siguiente paso', type: 'percentage', min: 0, max: 20, step: 0.1, benchmark: 'Promedio: 1-3%' },
    ],
  },

  organicPost: {
    type: 'organicPost',
    label: 'Post Orgánico',
    category: 'traffic',
    description: 'Publicaciones orgánicas en redes sociales',
    icon: 'Image',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'instagram', reach: 5000, engagementRate: 4, ctr: 1.5 },
    fields: [
      { key: 'platform', label: 'Plataforma', type: 'text', tooltip: 'Red social' },
      { key: 'reach', label: 'Alcance mensual', type: 'number', min: 0, max: 10000000, step: 100 },
      { key: 'engagementRate', label: 'Engagement', type: 'percentage', min: 0, max: 100, step: 0.1, benchmark: 'Instagram: 2-6% | Facebook: 1-3%' },
      { key: 'ctr', label: 'CTR a siguiente paso', type: 'percentage', min: 0, max: 20, step: 0.1 },
    ],
  },

  podcast: {
    type: 'podcast',
    label: 'Podcast',
    category: 'traffic',
    description: 'Tráfico desde episodios de podcast',
    icon: 'Mic',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'spotify', reach: 3000, engagementRate: 60, ctr: 5 },
    fields: [
      { key: 'platform', label: 'Plataforma', type: 'text', tooltip: 'Plataforma del podcast' },
      { key: 'reach', label: 'Escuchas mensuales', type: 'number', min: 0, max: 10000000, step: 100 },
      { key: 'engagementRate', label: 'Retención promedio', type: 'percentage', min: 0, max: 100, step: 1, benchmark: 'Podcast típico: 50-70%' },
      { key: 'ctr', label: 'CTR a siguiente paso', type: 'percentage', min: 0, max: 30, step: 0.5, benchmark: 'Podcast con CTA claro: 3-8%' },
    ],
  },

  influencer: {
    type: 'influencer',
    label: 'Influencer / Afiliado',
    category: 'traffic',
    description: 'Tráfico referido por influencer o afiliado',
    icon: 'Star',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'instagram', reach: 50000, engagementRate: 3, ctr: 1 },
    fields: [
      { key: 'platform', label: 'Plataforma', type: 'text' },
      { key: 'reach', label: 'Audiencia del influencer', type: 'number', min: 0, max: 100000000, step: 1000, benchmark: 'Nano: 1k-10k | Macro: 100k+' },
      { key: 'engagementRate', label: 'Engagement', type: 'percentage', min: 0, max: 100, step: 0.1 },
      { key: 'ctr', label: 'CTR estimado', type: 'percentage', min: 0, max: 20, step: 0.1, benchmark: 'Nano influencer: 2-5% | Macro: 0.5-2%' },
    ],
  },

  community: {
    type: 'community',
    label: 'Comunidad / Grupo',
    category: 'traffic',
    description: 'Tráfico desde grupos y comunidades online',
    icon: 'Users',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'facebook', reach: 2000, engagementRate: 10, ctr: 3 },
    fields: [
      { key: 'platform', label: 'Plataforma', type: 'text', tooltip: 'Facebook Groups, Discord, Slack, etc.' },
      { key: 'reach', label: 'Miembros activos', type: 'number', min: 0, max: 1000000, step: 100 },
      { key: 'engagementRate', label: 'Tasa de engagement', type: 'percentage', min: 0, max: 100, step: 0.5 },
      { key: 'ctr', label: 'CTR al funnel', type: 'percentage', min: 0, max: 30, step: 0.5 },
    ],
  },

  pr: {
    type: 'pr',
    label: 'PR / Medios',
    category: 'traffic',
    description: 'Tráfico desde prensa, notas y apariciones en medios',
    icon: 'Globe',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'web', reach: 20000, engagementRate: 2, ctr: 1 },
    fields: [
      { key: 'platform', label: 'Tipo de medio', type: 'text', tooltip: 'Blog, revista, periódico, TV, etc.' },
      { key: 'reach', label: 'Audiencia del medio', type: 'number', min: 0, max: 100000000, step: 1000 },
      { key: 'engagementRate', label: 'Tasa de lectura/visionado', type: 'percentage', min: 0, max: 100, step: 0.1 },
      { key: 'ctr', label: 'CTR al sitio', type: 'percentage', min: 0, max: 20, step: 0.1 },
    ],
  },

  marketplace: {
    type: 'marketplace',
    label: 'Marketplace',
    category: 'traffic',
    description: 'Tráfico desde marketplaces (Amazon, Mercado Libre, etc.)',
    icon: 'ShoppingBag',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'amazon', reach: 8000, engagementRate: 5, ctr: 3 },
    fields: [
      { key: 'platform', label: 'Marketplace', type: 'text' },
      { key: 'reach', label: 'Impresiones mensuales', type: 'number', min: 0, max: 10000000, step: 100 },
      { key: 'engagementRate', label: 'CTR producto', type: 'percentage', min: 0, max: 30, step: 0.1, benchmark: 'Amazon: 3-8%' },
      { key: 'ctr', label: 'CTR a funnel externo', type: 'percentage', min: 0, max: 20, step: 0.1 },
    ],
  },

  qrOffline: {
    type: 'qrOffline',
    label: 'QR / Offline',
    category: 'traffic',
    description: 'Tráfico desde medios físicos con código QR',
    icon: 'QrCode',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { platform: 'flyer', reach: 1000, engagementRate: 5, ctr: 5 },
    fields: [
      { key: 'platform', label: 'Soporte físico', type: 'text', tooltip: 'Flyer, cartel, producto, evento, etc.' },
      { key: 'reach', label: 'Distribución mensual', type: 'number', min: 0, max: 1000000, step: 100 },
      { key: 'engagementRate', label: 'Tasa de escaneo QR', type: 'percentage', min: 0, max: 30, step: 0.5, benchmark: 'QR en evento: 5-15%' },
      { key: 'ctr', label: 'CTR al funnel', type: 'percentage', min: 0, max: 30, step: 0.5 },
    ],
  },

  linkedinAds: {
    type: 'linkedinAds',
    label: 'LinkedIn Ads',
    category: 'traffic',
    description: 'Publicidad pagada en LinkedIn',
    icon: 'Briefcase',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { budget: 500, cpm: 30, ctr: 0.6, platform: 'linkedin' },
    fields: [
      { key: 'budget', label: 'Presupuesto mensual', type: 'currency', min: 0, max: 100000, step: 100 },
      { key: 'cpm', label: 'CPM', type: 'currency', min: 1, max: 200, step: 1, benchmark: 'LinkedIn: $20-$60 CPM' },
      { key: 'ctr', label: 'CTR', type: 'percentage', min: 0.1, max: 10, step: 0.1, benchmark: 'LinkedIn Ads: 0.4-0.9%' },
    ],
  },

  twitterAds: {
    type: 'twitterAds',
    label: 'X / Twitter Ads',
    category: 'traffic',
    description: 'Publicidad pagada en X (Twitter)',
    icon: 'Hash',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { budget: 300, cpm: 8, ctr: 1, platform: 'twitter' },
    fields: [
      { key: 'budget', label: 'Presupuesto mensual', type: 'currency', min: 0, max: 100000, step: 100 },
      { key: 'cpm', label: 'CPM', type: 'currency', min: 1, max: 100, step: 0.5, benchmark: 'Twitter: $6-$12 CPM' },
      { key: 'ctr', label: 'CTR', type: 'percentage', min: 0.1, max: 10, step: 0.1, benchmark: 'Twitter Ads: 0.5-2%' },
    ],
  },

  pinterestAds: {
    type: 'pinterestAds',
    label: 'Pinterest Ads',
    category: 'traffic',
    description: 'Publicidad pagada en Pinterest',
    icon: 'Image',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { budget: 300, cpm: 5, ctr: 0.5, platform: 'pinterest' },
    fields: [
      { key: 'budget', label: 'Presupuesto mensual', type: 'currency', min: 0, max: 100000, step: 100 },
      { key: 'cpm', label: 'CPM', type: 'currency', min: 1, max: 50, step: 0.5, benchmark: 'Pinterest: $3-$8 CPM' },
      { key: 'ctr', label: 'CTR', type: 'percentage', min: 0.1, max: 10, step: 0.1, benchmark: 'Pinterest Ads: 0.3-0.7%' },
    ],
  },

  youtubeAds: {
    type: 'youtubeAds',
    label: 'YouTube Ads',
    category: 'traffic',
    description: 'Publicidad pagada en YouTube (pre-roll, bumper)',
    icon: 'CirclePlay',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { budget: 500, cpm: 7, ctr: 1.5, platform: 'youtube' },
    fields: [
      { key: 'budget', label: 'Presupuesto mensual', type: 'currency', min: 0, max: 100000, step: 100 },
      { key: 'cpm', label: 'CPM', type: 'currency', min: 1, max: 50, step: 0.5, benchmark: 'YouTube: $4-$12 CPM' },
      { key: 'ctr', label: 'CTR', type: 'percentage', min: 0.1, max: 10, step: 0.1, benchmark: 'YouTube Ads: 0.5-2%' },
    ],
  },

  // ─── Content & Engagement ──────────────────────────────────────────────────

  blogSeo: {
    type: 'blogSeo',
    label: 'Blog / SEO',
    category: 'content',
    description: 'Artículos de blog optimizados para SEO',
    icon: 'BookOpen',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { monthlyVisits: 5000, avgTimeOnPage: 120, scrollDepth: 55, ctrToCta: 3.5 },
    fields: [],
  },

  videoContent: {
    type: 'videoContent',
    label: 'Video Content',
    category: 'content',
    description: 'Contenido de video (YouTube, Vimeo, etc.)',
    icon: 'Video',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { monthlyViews: 8000, watchTimePct: 45, ctrToCta: 4, subscriptionRate: 2, videoPlatform: 'youtube' },
    fields: [],
  },

  leadMagnet: {
    type: 'leadMagnet',
    label: 'Lead Magnet',
    category: 'content',
    description: 'Recurso gratuito para capturar leads',
    icon: 'Download',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { optInRate: 35, leadQualityScore: 6, magnetType: 'pdf' },
    fields: [],
  },

  quizInteractive: {
    type: 'quizInteractive',
    label: 'Quiz Interactivo',
    category: 'content',
    description: 'Quiz para segmentar y calificar leads',
    icon: 'Info',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { startRate: 60, completionRate: 70, segments: 3, optInAtEnd: 45 },
    fields: [],
  },

  calculatorTool: {
    type: 'calculatorTool',
    label: 'Calculadora / Herramienta',
    category: 'content',
    description: 'Herramienta interactiva para calificar leads',
    icon: 'Calculator',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { monthlyUses: 2000, avgUsageTimeSec: 180, nextStepConversion: 12 },
    fields: [],
  },

  educationalCarousel: {
    type: 'educationalCarousel',
    label: 'Carrusel Educativo',
    category: 'content',
    description: 'Carrusel de slides educativos en redes sociales',
    icon: 'LayoutList',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { avgSwipes: 6, saveRate: 5, shareRate: 2, ctrToLink: 1.5 },
    fields: [],
  },

  ebookGuide: {
    type: 'ebookGuide',
    label: 'Ebook / Guía',
    category: 'content',
    description: 'Ebook o guía descargable para captura de leads',
    icon: 'BookOpen',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { avgPagesPct: 35, ctrToOffer: 5 },
    fields: [],
  },

  resourceTemplate: {
    type: 'resourceTemplate',
    label: 'Template / Recurso',
    category: 'content',
    description: 'Plantilla o recurso descargable gratuito',
    icon: 'FileDown',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { downloadRate: 40, actualUseRate: 30, postUseConversion: 8 },
    fields: [],
  },

  webinarReplay: {
    type: 'webinarReplay',
    label: 'Replay de Webinar',
    category: 'content',
    description: 'Grabación de webinar para nurturing',
    icon: 'Video',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { viewsPct: 25, watchTimePct: 40, ctrToOffer: 6, conversionRate: 4 },
    fields: [],
  },

  caseStudy: {
    type: 'caseStudy',
    label: 'Caso de Éxito',
    category: 'content',
    description: 'Caso de éxito para nutrir y convertir prospectos',
    icon: 'FileText',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { avgReadTimeSec: 180, ctrToCta: 8 },
    fields: [],
  },

  // ─── AI Agents ─────────────────────────────────────────────────────────────

  aiWhatsapp: {
    type: 'aiWhatsapp',
    label: 'Agente IA WhatsApp',
    category: 'ai',
    description: 'Agente de IA para atención y ventas por WhatsApp',
    icon: 'Bot',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { messagesPerMonth: 500, autoResponseRate: 85, humanHandoffRate: 15, conversionRate: 12, costPerConversation: 0.05 },
    fields: [],
  },

  aiWebChat: {
    type: 'aiWebChat',
    label: 'Agente IA Web Chat',
    category: 'ai',
    description: 'Chatbot con IA en el sitio web',
    icon: 'Bot',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { sessionsPerMonth: 1000, autoResolutionRate: 70, humanEscalationRate: 20, leadsGeneratedRate: 15, csatScore: 4.2 },
    fields: [],
  },

  aiVoice: {
    type: 'aiVoice',
    label: 'Agente IA Voz',
    category: 'ai',
    description: 'Agente de voz con IA para llamadas entrantes/salientes',
    icon: 'Phone',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { callsAttendedPerMonth: 300, avgCallDurationSec: 120, resolutionRate: 60, bookingRate: 20, costPerCall: 0.15 },
    fields: [],
  },

  aiInstagramDm: {
    type: 'aiInstagramDm',
    label: 'Agente IA Instagram DM',
    category: 'ai',
    description: 'Agente de IA para mensajes directos en Instagram',
    icon: 'Bot',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { dmsProcessedPerMonth: 800, autoResponseRate: 80, linkConversionRate: 18, postResponseEngagement: 25 },
    fields: [],
  },

  aiEmail: {
    type: 'aiEmail',
    label: 'Agente IA Email',
    category: 'ai',
    description: 'Automatización de email con IA personalizada',
    icon: 'Bot',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { emailsProcessedPerMonth: 2000, autoResponseRate: 75, autoFollowUpRate: 40, resolutionRate: 55 },
    fields: [],
  },

  chatbotRules: {
    type: 'chatbotRules',
    label: 'Chatbot por Reglas',
    category: 'ai',
    description: 'Chatbot basado en flujo de reglas predefinidas',
    icon: 'Bot',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { interactionsPerMonth: 1500, flowCompletionRate: 55, fallbackRate: 20, leadsCapturedRate: 25 },
    fields: [],
  },

  automationWorkflow: {
    type: 'automationWorkflow',
    label: 'Workflow de Automatización',
    category: 'ai',
    description: 'Automatización de procesos con lógica condicional',
    icon: 'Workflow',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { executionsPerMonth: 5000, successRate: 95, timeSavedHrsPerMonth: 40, operatingCostPerMonth: 30 },
    fields: [],
  },

  aiLeadScoring: {
    type: 'aiLeadScoring',
    label: 'Lead Scoring IA',
    category: 'ai',
    description: 'Calificación automática de leads con IA',
    icon: 'Target',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { scoringPrecision: 75, mqlRate: 30, avgResponseTimeMin: 5 },
    fields: [],
  },

  aiContentPersonalization: {
    type: 'aiContentPersonalization',
    label: 'Personalización IA',
    category: 'ai',
    description: 'Personalización de contenido con IA según comportamiento',
    icon: 'Sparkles',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { variantsGenerated: 5, ctrLift: 25, conversionLift: 15 },
    fields: [],
  },

  aiSegmentation: {
    type: 'aiSegmentation',
    label: 'Segmentación IA',
    category: 'ai',
    description: 'Segmentación automática de audiencias con IA',
    icon: 'Layers',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { segmentsCreated: 5, segmentationPrecision: 80 },
    fields: [],
  },

  // ─── Tracking ──────────────────────────────────────────────────────────────

  metaPixel: {
    type: 'metaPixel',
    label: 'Meta Pixel',
    category: 'tracking',
    description: 'Pixel de Meta para tracking de conversiones',
    icon: 'Code',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { trackedEvents: ['ViewContent', 'Lead'], matchQualityScore: 85, capiEnabled: false },
    fields: [],
  },

  googleTagManager: {
    type: 'googleTagManager',
    label: 'Google Tag Manager',
    category: 'tracking',
    description: 'Gestión centralizada de tags y tracking',
    icon: 'Code',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { activeTags: 10, configuredTriggers: 15, gtmPagesCoverage: 90 },
    fields: [],
  },

  googleAnalytics: {
    type: 'googleAnalytics',
    label: 'Google Analytics',
    category: 'tracking',
    description: 'Analytics de Google para métricas web',
    icon: 'BarChart3',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { gaConfiguredEvents: 20, gaConversions: 5, gaAttributionModel: 'lastClick' },
    fields: [],
  },

  metaOfflineData: {
    type: 'metaOfflineData',
    label: 'Meta Offline Data',
    category: 'tracking',
    description: 'Conversiones offline enviadas a Meta',
    icon: 'Database',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { offlineEventsPerMonth: 500, offlineMatchRate: 70, uploadDelayDays: 3 },
    fields: [],
  },

  utmTracking: {
    type: 'utmTracking',
    label: 'UTM Tracking',
    category: 'tracking',
    description: 'Parámetros UTM para atribución de campañas',
    icon: 'Tag',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { utmSource: '', utmMedium: '', utmCampaign: '', utmContent: '', utmTerm: '' },
    fields: [],
  },

  serverPostback: {
    type: 'serverPostback',
    label: 'Server Postback',
    category: 'tracking',
    description: 'Postback server-to-server para tracking preciso',
    icon: 'Server',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { connectedPlatforms: ['meta'], precisionVsCookie: 95, postbackConversionsPerMonth: 1000 },
    fields: [],
  },

  crmAttribution: {
    type: 'crmAttribution',
    label: 'CRM Attribution',
    category: 'tracking',
    description: 'Atribución multi-touch a través del CRM',
    icon: 'Network',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { crmAttributionModel: 'lastTouch', crmAttributedRevenue: 10000 },
    fields: [],
  },

  heatmaps: {
    type: 'heatmaps',
    label: 'Heatmaps / Grabaciones',
    category: 'tracking',
    description: 'Mapas de calor y grabaciones de sesión',
    icon: 'Activity',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { heatmapTool: 'hotjar', heatmapSessionsPerMonth: 1000, rageClicksRate: 5 },
    fields: [],
  },

  callTracking: {
    type: 'callTracking',
    label: 'Call Tracking',
    category: 'tracking',
    description: 'Seguimiento de llamadas para atribución',
    icon: 'Phone',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { trackedCallsPerMonth: 200, callSourceAttribution: 75, callAvgDurationSec: 180, postCallConversion: 15 },
    fields: [],
  },

  conversionApi: {
    type: 'conversionApi',
    label: 'Conversions API',
    category: 'tracking',
    description: 'API de conversiones server-side (Meta CAPI, Google, etc.)',
    icon: 'Zap',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { serverEventsPerMonth: 5000, pixelRedundancyPct: 20, deduplicationRate: 95 },
    fields: [],
  },

  // ─── New pages ─────────────────────────────────────────────────────────────

  applicationPage: {
    type: 'applicationPage',
    label: 'Página de Aplicación',
    category: 'pages',
    description: 'Formulario de aplicación para calificar prospectos',
    icon: 'FileText',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { completionRate: 35, qualificationRate: 60, formFields: 8 },
    fields: [],
  },

  tripwire: {
    type: 'tripwire',
    label: 'Tripwire / Oferta Entrada',
    category: 'pages',
    description: 'Oferta de bajo precio para convertir leads en compradores',
    icon: 'CreditCard',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { price: 7, conversionRate: 8, processorFee: 3.5 },
    fields: [],
  },

  catalogStore: {
    type: 'catalogStore',
    label: 'Catálogo / Tienda',
    category: 'pages',
    description: 'Tienda o catálogo de productos',
    icon: 'ShoppingBag',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { avgProductsViewed: 3.5, addToCartRate: 8, aov: 65, bounceRate: 45 },
    fields: [],
  },

  pricingPage: {
    type: 'pricingPage',
    label: 'Página de Precios',
    category: 'pages',
    description: 'Página con planes y comparación de precios',
    icon: 'DollarSign',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { conversionRate: 12, popularPlan: 'pro', annualPct: 35, avgTimeOnPage: 90 },
    fields: [],
  },

  freeTrialSignup: {
    type: 'freeTrialSignup',
    label: 'Registro Prueba Gratuita',
    category: 'pages',
    description: 'Registro para prueba gratuita de producto/servicio',
    icon: 'Gift',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { signupRate: 15, activationRate: 40, trialDays: 14 },
    fields: [],
  },

  thankYouOffer: {
    type: 'thankYouOffer',
    label: 'Thank You + Oferta',
    category: 'pages',
    description: 'Página de gracias con oferta adicional',
    icon: 'Award',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { conversionRate: 12, price: 47, contentEngagementRate: 65, processorFee: 3.5 },
    fields: [],
  },

  // ─── Follow-up ─────────────────────────────────────────────────────────────

  pushNotifications: {
    type: 'pushNotifications',
    label: 'Push Notifications',
    category: 'followup',
    description: 'Notificaciones push web o mobile',
    icon: 'Bell',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { optInRate: 45, deliveryRate: 90, ctr: 4, postClickConversion: 8 },
    fields: [],
  },

  dynamicRetargeting: {
    type: 'dynamicRetargeting',
    label: 'Retargeting Dinámico',
    category: 'followup',
    description: 'Retargeting con anuncios dinámicos personalizados',
    icon: 'RefreshCw',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { budget: 200, cpc: 0.40, ctr: 2.5, postClickConversion: 5, attributionWindow: 7 },
    fields: [],
  },

  multichannelNurturing: {
    type: 'multichannelNurturing',
    label: 'Nurturing Multicanal',
    category: 'followup',
    description: 'Secuencia de nurturing coordinada en múltiples canales',
    icon: 'Layers',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { activeChannels: ['email', 'whatsapp'], touchpoints: 8, conversionRate: 12, nurturingDays: 30, monthlyCost: 50 },
    fields: [],
  },

  cartAbandonmentSeq: {
    type: 'cartAbandonmentSeq',
    label: 'Recuperación Carrito',
    category: 'followup',
    description: 'Secuencia de recuperación de carritos abandonados',
    icon: 'ShoppingBag',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { emailCount: 3, openRate: 45, recoveryRate: 10, avgCartValue: 85 },
    fields: [],
  },

  reEngagement: {
    type: 'reEngagement',
    label: 'Re-Engagement',
    category: 'followup',
    description: 'Campaña para reactivar leads fríos o inactivos',
    icon: 'RotateCcw',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { inactiveReached: 1000, reactivationRate: 5, costPerReactivation: 2, reactivationChannel: 'email' },
    fields: [],
  },

  dripCampaign: {
    type: 'dripCampaign',
    label: 'Drip Campaign',
    category: 'followup',
    description: 'Campaña de goteo con emails educativos y de ventas',
    icon: 'Mail',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { duration: '2months', emailCount: 12, openRate: 22, ctr: 2.5, sustainedEngagement: 40, eventualConversion: 5 },
    fields: [],
  },

  // ─── Sales ─────────────────────────────────────────────────────────────────

  outboundCall: {
    type: 'outboundCall',
    label: 'Llamada Saliente',
    category: 'sales',
    description: 'Llamadas salientes del equipo comercial',
    icon: 'PhoneOutgoing',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { callsPerDay: 30, contactRate: 25, conversationRate: 40, closeRate: 15, avgTicket: 500 },
    fields: [],
  },

  inboundCall: {
    type: 'inboundCall',
    label: 'Llamada Entrante',
    category: 'sales',
    description: 'Llamadas entrantes de prospectos interesados',
    icon: 'PhoneIncoming',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { answeredRate: 85, closeRate: 30, avgTicket: 350 },
    fields: [],
  },

  salesProposal: {
    type: 'salesProposal',
    label: 'Propuesta Comercial',
    category: 'sales',
    description: 'Propuesta formal enviada al prospecto',
    icon: 'FileText',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { openRate: 80, acceptanceRate: 25, avgPrice: 2500, avgDaysToClose: 14 },
    fields: [],
  },

  productDemo: {
    type: 'productDemo',
    label: 'Demo de Producto',
    category: 'sales',
    description: 'Demostración del producto o servicio',
    icon: 'Monitor',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { showRate: 70, followUpRate: 50, closeRate: 20, avgPrice: 1200 },
    fields: [],
  },

  trialToPaid: {
    type: 'trialToPaid',
    label: 'Trial a Pago',
    category: 'sales',
    description: 'Conversión de usuarios de prueba a clientes pagos',
    icon: 'CreditCard',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { conversionRate: 15, price: 29, priceType: 'monthly', avgDaysToConvert: 10 },
    fields: [],
  },

  physicalPos: {
    type: 'physicalPos',
    label: 'Punto de Venta Físico',
    category: 'sales',
    description: 'Venta en tienda o punto de venta físico',
    icon: 'MapPin',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { walkInsPerMonth: 500, conversionRate: 25, avgTicket: 85, repeatRate: 20 },
    fields: [],
  },

  digitalContract: {
    type: 'digitalContract',
    label: 'Contrato Digital',
    category: 'sales',
    description: 'Firma de contrato digital para cerrar la venta',
    icon: 'FileCheck',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { signedRate: 65, contractValue: 3000, avgDaysToSign: 7 },
    fields: [],
  },

  salesNegotiation: {
    type: 'salesNegotiation',
    label: 'Negociación de Ventas',
    category: 'sales',
    description: 'Proceso de negociación con el prospecto',
    icon: 'Handshake',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { winRate: 30, avgDiscountPct: 10, salesCycleDays: 30 },
    fields: [],
  },

  eventSales: {
    type: 'eventSales',
    label: 'Evento / Lanzamiento',
    category: 'sales',
    description: 'Venta en evento presencial o lanzamiento online',
    icon: 'Calendar',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { attendees: 200, leadsContactedRate: 15, followUpRate: 60, closeRate: 10, avgTicket: 800 },
    fields: [],
  },

  // ─── Post-sale ─────────────────────────────────────────────────────────────

  onboardingSeq: {
    type: 'onboardingSeq',
    label: 'Secuencia de Onboarding',
    category: 'postsale',
    description: 'Secuencia de bienvenida y activación de nuevos clientes',
    icon: 'Rocket',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { completionRate: 60, timeToValueDays: 7, activationRate: 45, onboardingSteps: 5 },
    fields: [],
  },

  reviewRequest: {
    type: 'reviewRequest',
    label: 'Solicitud de Reseña',
    category: 'postsale',
    description: 'Pedido de valoración o reseña al cliente satisfecho',
    icon: 'Star',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { responseRate: 15, avgRating: 4.5, platform: 'google' },
    fields: [],
  },

  referralProgram: {
    type: 'referralProgram',
    label: 'Programa de Referidos',
    category: 'postsale',
    description: 'Programa de referidos para clientes existentes',
    icon: 'Share2',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { invitationsPerCustomer: 3, referralConversionRate: 15, cacReduction: 30, rewardCost: 10 },
    fields: [],
  },

  renewalUpsell: {
    type: 'renewalUpsell',
    label: 'Renovación / Upsell',
    category: 'postsale',
    description: 'Renovación de contrato o upgrade de plan',
    icon: 'RefreshCw',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { churnRate: 5, upgradeRate: 8, renewalPrice: 29, upgradePrice: 79, ltvIncrease: 35 },
    fields: [],
  },

  postSaleSupport: {
    type: 'postSaleSupport',
    label: 'Soporte Post-Venta',
    category: 'postsale',
    description: 'Atención al cliente después de la venta',
    icon: 'Headphones',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { ticketsPerMonth: 50, resolutionRate: 85, csatScore: 7.5, repurchaseImpact: 15 },
    fields: [],
  },

  customerCommunity: {
    type: 'customerCommunity',
    label: 'Comunidad de Clientes',
    category: 'postsale',
    description: 'Comunidad privada para clientes (retención y upsell)',
    icon: 'Users',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { activeMembersRate: 30, monthlyEngagement: 15, retentionLift: 20, communityReferrals: 5 },
    fields: [],
  },

  crossSell: {
    type: 'crossSell',
    label: 'Cross-sell',
    category: 'postsale',
    description: 'Venta cruzada de productos complementarios',
    icon: 'TrendingUp',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { acceptanceRate: 12, price: 45 },
    fields: [],
  },

  winBack: {
    type: 'winBack',
    label: 'Win-Back',
    category: 'postsale',
    description: 'Campaña para recuperar clientes perdidos',
    icon: 'RotateCcw',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { reactivationRate: 8, reactivationCost: 15, restoredLtv: 150 },
    fields: [],
  },

  loyaltyProgram: {
    type: 'loyaltyProgram',
    label: 'Programa de Lealtad',
    category: 'postsale',
    description: 'Programa de puntos o fidelización de clientes',
    icon: 'Award',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { participationRate: 40, redemptionRate: 25, purchaseFrequencyLift: 18, programCostPerCustomer: 5 },
    fields: [],
  },

  npsSurvey: {
    type: 'npsSurvey',
    label: 'Encuesta NPS',
    category: 'postsale',
    description: 'Net Promoter Score para medir satisfacción',
    icon: 'ClipboardList',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { responseRate: 25, npsScore: 45, detractorsRate: 15, detractorActionRate: 50 },
    fields: [],
  },

  // ─── Utilities ─────────────────────────────────────────────────────────────

  delayWait: {
    type: 'delayWait',
    label: 'Espera / Delay',
    category: 'utilities',
    description: 'Pausa en el flujo — todos los contactos pasan',
    icon: 'Clock',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { days: 3, dropOffRate: 0, unit: 'days' },
    fields: [],
  },

  conditionalBranch: {
    type: 'conditionalBranch',
    label: 'Rama Condicional',
    category: 'utilities',
    description: 'Divide el flujo en sí/no según una condición',
    icon: 'GitBranch',
    hasYesNoOutput: true,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { branchCondition: 'Lead score > 50', yesPercent: 40 },
    fields: [],
  },

  mergeNode: {
    type: 'mergeNode',
    label: 'Merge / Unión',
    category: 'utilities',
    description: 'Une múltiples flujos en uno solo',
    icon: 'Merge',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: {},
    fields: [],
  },

  stickyNote: {
    type: 'stickyNote',
    label: 'Nota',
    category: 'utilities',
    description: 'Nota de texto para documentar el funnel',
    icon: 'StickyNote',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { text: '', color: '#fef08a' },
    fields: [
      { key: 'text', label: 'Texto de la nota', type: 'text', tooltip: 'Agrega comentarios o instrucciones' },
      { key: 'color', label: 'Color', type: 'text', tooltip: 'Color de fondo en hex' },
    ],
  },

  kpiCheckpoint: {
    type: 'kpiCheckpoint',
    label: 'KPI Checkpoint',
    category: 'utilities',
    description: 'Punto de medición de KPI en el funnel',
    icon: 'Target',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { kpiName: 'CPA', kpiAlertThreshold: 15, kpiAlertType: 'above' },
    fields: [],
  },

  abSplitTest: {
    type: 'abSplitTest',
    label: 'A/B Split Test',
    category: 'utilities',
    description: 'Test A/B para comparar dos variantes',
    icon: 'Shuffle',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: true,
    hasInput: true,
    defaultConfig: {
      branches: [
        { id: 'branch-0', label: 'Variante A', percentage: 50 },
        { id: 'branch-1', label: 'Variante B', percentage: 50 },
      ],
    },
    fields: [],
  },

  loopRecurrence: {
    type: 'loopRecurrence',
    label: 'Loop / Recurrencia',
    category: 'utilities',
    description: 'Ciclo recurrente (ej: mensual, semanal)',
    icon: 'Repeat',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { iterations: 12, loopFrequency: 'monthly', retentionPerCycle: 90 },
    fields: [],
  },

  groupContainer: {
    type: 'groupContainer',
    label: 'Contenedor / Grupo',
    category: 'utilities',
    description: 'Agrupa nodos visualmente',
    icon: 'Square',
    hasYesNoOutput: false,
    hasSingleOutput: false,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: { text: 'Grupo', color: '#1e293b' },
    fields: [
      { key: 'text', label: 'Etiqueta del grupo', type: 'text' },
    ],
  },

  milestoneNode: {
    type: 'milestoneNode',
    label: 'Hito / Milestone',
    category: 'utilities',
    description: 'Marca un punto clave del funnel',
    icon: 'Flag',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { milestoneStage: 'awareness', milestoneDescription: '' },
    fields: [],
  },

  fixedCostNode: {
    type: 'fixedCostNode',
    label: 'Costo Fijo',
    category: 'utilities',
    description: 'Registra un costo fijo mensual del funnel',
    icon: 'DollarSign',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { costConcept: 'Hosting', monthlyCost: 100, isRecurring: true },
    fields: [],
  },

  recurringRevenueNode: {
    type: 'recurringRevenueNode',
    label: 'Ingresos Recurrentes',
    category: 'utilities',
    description: 'Modelo de ingresos recurrentes (MRR/suscripción)',
    icon: 'TrendingUp',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: true,
    defaultConfig: { mrr: 29, churnRate: 5, months: 12, growthRate: 3 },
    fields: [],
  },

  // ─── Traffic Entry — contenedor de fuentes de tráfico ─────────────────────

  trafficEntry: {
    type: 'trafficEntry',
    label: 'Fuente de tráfico',
    category: 'traffic',
    description: 'Contenedor que agrupa múltiples fuentes de tráfico pagado y orgánico',
    icon: 'Layers',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: {
      name: 'Fuente de tráfico',
      sources: [],
      totalVisitors: 0,
      totalPaidVisitors: 0,
      totalOrganicVisitors: 0,
      totalBudget: 0,
    },
    fields: [],
  },

  // ─── Nuevas fuentes de tráfico especializadas ──────────────────────────────

  paidTraffic: {
    type: 'paidTraffic',
    label: 'Tráfico Pagado',
    category: 'traffic',
    description: 'Anuncios pagados: Meta, Google, TikTok, LinkedIn y más',
    icon: 'Megaphone',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: {
      platform: 'meta',
      costModel: 'cpc',
      budget: 1000,
      cpc: 0.80,
      cpm: 8.50,
      cpv: 0.10,
      ctr: 1.5,
    },
    fields: [
      {
        key: 'platform',
        label: 'Plataforma',
        type: 'select',
        options: [
          { value: 'meta',          label: 'Meta Ads (Facebook / Instagram)' },
          { value: 'googleSearch',  label: 'Google Ads (Search)' },
          { value: 'googleDisplay', label: 'Google Ads (Display)' },
          { value: 'youtube',       label: 'Google Ads (YouTube)' },
          { value: 'tiktok',        label: 'TikTok Ads' },
          { value: 'linkedin',      label: 'LinkedIn Ads' },
          { value: 'twitter',       label: 'Twitter/X Ads' },
          { value: 'pinterest',     label: 'Pinterest Ads' },
          { value: 'other',         label: 'Otro' },
        ],
      },
      {
        key: 'costModel',
        label: 'Modelo de costo',
        type: 'select',
        options: [
          { value: 'cpc', label: 'CPC — Costo por clic' },
          { value: 'cpm', label: 'CPM — Costo por mil impresiones' },
          { value: 'cpv', label: 'CPV — Costo por vista (YouTube)' },
        ],
      },
      { key: 'budget', label: 'Presupuesto mensual', type: 'currency', min: 0, max: 1000000, step: 100, benchmark: 'Mínimo recomendado: $300-500/mes' },
      { key: 'cpc', label: 'CPC (costo por clic)', type: 'currency', min: 0.01, max: 100, step: 0.01, benchmark: 'Meta: $0.80 | Google Search: $2.50 | TikTok: $0.50' },
      { key: 'cpm', label: 'CPM (costo por mil)', type: 'currency', min: 0.1, max: 200, step: 0.5, benchmark: 'Meta: $8.50 | TikTok: $6.00 | LinkedIn: $30.00' },
      { key: 'cpv', label: 'CPV (costo por vista)', type: 'currency', min: 0.01, max: 1, step: 0.01, benchmark: 'YouTube: $0.10 promedio' },
      { key: 'ctr', label: 'CTR (%)', type: 'percentage', min: 0.1, max: 20, step: 0.1, benchmark: 'Meta: 1.5% | Google Search: 3.5% | LinkedIn: 0.8%' },
    ],
  },

  organicTraffic: {
    type: 'organicTraffic',
    label: 'Tráfico Orgánico',
    category: 'traffic',
    description: 'Alcance orgánico: Instagram, TikTok, YouTube, SEO, email, referidos y más',
    icon: 'Leaf',
    hasYesNoOutput: false,
    hasSingleOutput: true,
    hasBranchOutput: false,
    hasInput: false,
    defaultConfig: {
      channel: 'instagram',
      reach: 10000,
      engagementRate: 3,
      ctr: 2.0,
      listSize: 1000,
      openRate: 25,
      activeReferrers: 10,
      referralsPerReferrer: 5,
      referralConversionRate: 10,
    },
    fields: [
      {
        key: 'channel',
        label: 'Canal',
        type: 'select',
        options: [
          { value: 'instagram',  label: 'Instagram (Reels / Posts / Stories)' },
          { value: 'facebook',   label: 'Facebook (Posts / Videos)' },
          { value: 'tiktok',     label: 'TikTok (Videos orgánicos)' },
          { value: 'youtube',    label: 'YouTube (Videos orgánicos)' },
          { value: 'linkedin',   label: 'LinkedIn (Posts / Artículos)' },
          { value: 'blog',       label: 'Blog / SEO' },
          { value: 'podcast',    label: 'Podcast' },
          { value: 'pinterest',  label: 'Pinterest orgánico' },
          { value: 'emailList',  label: 'Lista de email existente' },
          { value: 'whatsapp',   label: 'WhatsApp broadcast' },
          { value: 'community',  label: 'Comunidad (grupo / foro)' },
          { value: 'referrals',  label: 'Referidos' },
          { value: 'other',      label: 'Otro' },
        ],
      },
      { key: 'reach', label: 'Alcance mensual (impresiones / views)', type: 'number', min: 0, max: 100000000, step: 1000, benchmark: 'Instagram Reels: 10K | TikTok: 15K | YouTube: 8K' },
      { key: 'engagementRate', label: 'Engagement rate (%)', type: 'percentage', min: 0, max: 100, step: 0.1, benchmark: 'Instagram: 2-5% | TikTok: 5-9% | LinkedIn: 1-3%' },
      { key: 'ctr', label: 'CTR a link / perfil (%)', type: 'percentage', min: 0, max: 50, step: 0.1, benchmark: 'Instagram: 2% | TikTok: 1.8% | YouTube: 3% | Podcast: 5%' },
      { key: 'listSize', label: 'Tamaño de lista (email)', type: 'number', min: 0, max: 10000000, step: 100 },
      { key: 'openRate', label: 'Open rate email (%)', type: 'percentage', min: 0, max: 100, step: 0.5, benchmark: 'Promedio LATAM: 22-32%' },
      { key: 'activeReferrers', label: 'Referidores activos', type: 'number', min: 0, max: 100000, step: 1 },
      { key: 'referralsPerReferrer', label: 'Referidos por referidor', type: 'number', min: 0, max: 100, step: 1 },
      { key: 'referralConversionRate', label: 'Conversión del referido (%)', type: 'percentage', min: 0, max: 100, step: 0.5 },
    ],
  },
}

// ─── Categorías para el sidebar ──────────────────────────────────────────────

export interface NodeCategory {
  id: string
  label: string
  color: typeof NODE_COLORS[string]
  nodes: FunnelNodeType[]
}

export const NODE_CATEGORIES: NodeCategory[] = [
  {
    id: 'traffic',
    label: 'Tráfico',
    color: NODE_COLORS.traffic,
    nodes: [
      'trafficEntry',
    ],
  },
  {
    id: 'pages',
    label: 'Páginas',
    color: NODE_COLORS.pages,
    nodes: [
      'landingPage', 'salesPage',
      'applicationPage', 'tripwire', 'catalogStore', 'pricingPage', 'freeTrialSignup', 'thankYouOffer',
    ],
  },
  {
    id: 'content',
    label: 'Contenido',
    color: NODE_COLORS.content,
    nodes: [
      'blogSeo', 'videoContent', 'leadMagnet', 'quizInteractive', 'calculatorTool',
      'educationalCarousel', 'ebookGuide', 'resourceTemplate', 'webinarReplay', 'caseStudy',
    ],
  },
  {
    id: 'ai',
    label: 'Agentes IA',
    color: NODE_COLORS.ai,
    nodes: [
      'aiWhatsapp', 'aiWebChat', 'aiVoice', 'aiInstagramDm', 'aiEmail',
      'chatbotRules', 'automationWorkflow', 'aiLeadScoring', 'aiContentPersonalization', 'aiSegmentation',
    ],
  },
  {
    id: 'tracking',
    label: 'Tracking',
    color: NODE_COLORS.tracking,
    nodes: [
      'metaPixel', 'googleTagManager', 'googleAnalytics', 'metaOfflineData', 'utmTracking',
      'serverPostback', 'crmAttribution', 'heatmaps', 'callTracking', 'conversionApi',
    ],
  },
  {
    id: 'sales',
    label: 'Ventas',
    color: NODE_COLORS.sales,
    nodes: [
      'checkout', 'upsell', 'downsell', 'orderBump', 'appointment',
      'outboundCall', 'inboundCall', 'salesProposal', 'productDemo', 'trialToPaid',
      'physicalPos', 'digitalContract', 'salesNegotiation', 'eventSales',
    ],
  },
  {
    id: 'followup',
    label: 'Follow-up',
    color: NODE_COLORS.followup,
    nodes: [
      'emailSequence', 'whatsappSms', 'webinarVsl',
      'pushNotifications', 'dynamicRetargeting', 'multichannelNurturing',
      'cartAbandonmentSeq', 'reEngagement', 'dripCampaign',
    ],
  },
  {
    id: 'postsale',
    label: 'Post-venta',
    color: NODE_COLORS.postsale,
    nodes: [
      'onboardingSeq', 'reviewRequest', 'referralProgram', 'renewalUpsell',
      'postSaleSupport', 'customerCommunity', 'crossSell', 'winBack', 'loyaltyProgram', 'npsSurvey',
    ],
  },
  {
    id: 'utilities',
    label: 'Utilidades',
    color: NODE_COLORS.utilities,
    nodes: [
      'split', 'result',
      'delayWait', 'conditionalBranch', 'mergeNode', 'stickyNote', 'kpiCheckpoint',
      'abSplitTest', 'loopRecurrence', 'groupContainer', 'milestoneNode', 'fixedCostNode', 'recurringRevenueNode',
    ],
  },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getNodeDef(type: FunnelNodeType): NodeDefinition {
  return NODE_DEFINITIONS[type]
}

export function getNodeColor(type: FunnelNodeType) {
  const def = NODE_DEFINITIONS[type]
  return NODE_COLORS[def.category]
}

export function getCategoryForType(type: FunnelNodeType): string {
  return NODE_DEFINITIONS[type].category
}
